services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgres://user:password@db:5432/dbname"
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_params:/etc/nginx/proxy_params
      - /home/django/myapp/static:/home/django/myapp/static
    depends_on:
      - web

volumes:
  postgres_data:
