# Generated by Django 4.2.6 on 2025-02-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("mep_count", models.SmallIntegerField(blank=True, null=True)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimMep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("EPP", "European People's Party"),
                            ("S&D", "Progressive Alliance of Socialists and Democrats"),
                            ("PfE", "Patriots for Europe"),
                            ("ECR", "European Conservatives and Reformists"),
                            ("Renew Europe", "Renew Europe"),
                            ("Greens/EFA", "The Greens/European Free Alliance"),
                            (
                                "The Left",
                                "The Left in the European Parliament - GUE/NGL",
                            ),
                            ("ESN", "Europe of Sovereign Nations"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("DS", "Dolnośląskie"),
                            ("KP", "Kujawsko-Pomorskie"),
                            ("LB", "Lubuskie"),
                            ("LD", "Łódzkie"),
                            ("LU", "Lubelskie"),
                            ("MA", "Małopolskie"),
                            ("MZ", "Mazowieckie"),
                            ("OP", "Opolskie"),
                            ("PK", "Podkarpackie"),
                            ("PD", "Podlaskie"),
                            ("PM", "Pomorskie"),
                            ("SL", "Śląskie"),
                            ("SW", "Świętokrzyskie"),
                            ("WN", "Warmińsko-Mazurskie"),
                            ("WP", "Wielkopolskie"),
                            ("ZP", "Zachodniopomorskie"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_on_list", models.SmallIntegerField(blank=True, null=True)),
                ("mep_id", models.IntegerField()),
                ("parlimentary_term", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimPoliticalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("ideology", models.CharField(blank=True, max_length=200, null=True)),
                ("foundation_date", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(blank=True, max_length=20, null=True)),
                ("month", models.CharField(blank=True, max_length=20, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("time_of_the_day", models.TimeField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "time_strings",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dim_mep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.dimmep"
                    ),
                ),
                (
                    "dim_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dimsession",
                    ),
                ),
                (
                    "dim_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.dimtime"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=100, unique=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(null=True)),
                ("bill_type", models.IntegerField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=False)),
                ("active_since", models.DateField(blank=True, null=True)),
                ("active_till", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("voting_date", models.DateField()),
                ("summary", models.TextField(null=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "result",
                    models.CharField(
                        choices=[("Z", "Za"), ("P", "Przeciw"), ("W", "Wstrzymany")],
                        default="P",
                        max_length=3,
                    ),
                ),
                (
                    "dim_amendmend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.dimbill",
                    ),
                ),
                (
                    "dim_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.dimsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("Z", "Za"), ("P", "Przeciw"), ("W", "Wstrzymany")],
                        max_length=1,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="main.dimbill",
                    ),
                ),
                (
                    "dim_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dimsession",
                    ),
                ),
                (
                    "dim_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dimtime",
                    ),
                ),
                (
                    "member_of_parliament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="main.dimmep",
                    ),
                ),
            ],
            options={
                "unique_together": {("member_of_parliament", "bill")},
            },
        ),
    ]
