# Generated by Django 4.2.6 on 2023-11-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voting_date", models.DateField()),
                ("content", models.TextField(null=True)),
                ("summary", models.TextField(null=True)),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MemberOfParliament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("PO", "Platforma Obywatelska"),
                            ("PiS", "Prawo i Sprawiedliwość"),
                            ("Lewica", "Lewica"),
                            ("PSL", "Polskie Stronnictwo Ludowe"),
                            ("Konfederacja", "Konfederacja Wolność i Niepodległość"),
                            ("N", "Nowoczesna"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("DS", "Dolnośląskie"),
                            ("KP", "Kujawsko-Pomorskie"),
                            ("MZ", "Mazowieckie"),
                            ("WL", "Wielkopolskie"),
                            ("SL", "Śląskie"),
                            ("PM", "Pomorskie"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_on_list", models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("Z", "Za"), ("P", "Przeciw"), ("W", "Wstzymany")],
                        max_length=1,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.bill"
                    ),
                ),
                (
                    "member_of_parliament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.memberofparliament",
                    ),
                ),
            ],
            options={
                "unique_together": {("member_of_parliament", "bill")},
            },
        ),
    ]
